### ISSUE TITLE
bug: 单词拼写错误

### ISSUE THREAD

**Issue by Anwen-zww** [CSU-Apple-Lab/evalcsu#41]
**Describe the bug**
贡献指南的Review流程中有单词拼写错误。

**To Reproduce**
NULL

**Expected behavior**
将Rebiew改为Review

**Screenshots**
NULL

**Additional context**
NULL

**Assign the manager you email**
NULL

**Comment by Jacob953** [comment]
Good job!
You are qualified to fix this bug!
