### ISSUE TITLE
feature: 编写Git&Github新手指南

### ISSUE THREAD

**Issue by the-fall-moon** [CSU-Apple-Lab/evalcsu#46]
**Problem**
Git&Github 入门对于新手小白有一定难度，会对有意向本项目贡献评教或课设的同学形成一定障碍。

**Solution**
编写一份可以让新手对Git&Github操作和概念有一定了解的新手指南/教学

**Basic requirement**
1. 语言文字尽量浅显易懂
2. 介绍基础几个概念，如仓库、暂存区等
2. 覆盖clone、pull到push的基础流程

**Comment by Jacob953** [comment]
Thanks for your future contributions!
