### ISSUE TITLE
计算机学院：请求完成计算机科学与技术2019级部分

### ISSUE THREAD

**Issue by typedrandomly** [CSU-Apple-Lab/evalcsu#6]

**Comment by Jacob953** [comment]
**TO-DO List**

- [ ] Update more experimental reports
- [ ] Update more notes
- [ ] Much more professional evaluations

**Comment by Jacob953** [comment]
Thanks for your future contributions!

**Comment by Jacob953** [comment]
Congratulations! You are qualified to evaluate!
